steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile_fitbit', '-t', 'gcr.io/data-science-258408/p4-fitbit', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/data-science-258408/p4-fitbit']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'p4-services-fitbit'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--image'
    - 'gcr.io/data-science-258408/p4-fitbit'
    - '--memory'
    - '512'
    - '--port'
    - '80'
    - '--allow-unauthenticated'
timeout: 1200s
images:
- gcr.io/data-science-258408/p4-fitbit
